repos:
  - repo: local
    hooks:
      - id: gotests
        name: Go tests
        entry: go test ./... -v
        language: system
        always_run: true
      - id: goimports
        name: GoImports code style
        entry: goimports -local "github.com/bubaew95/go_shop" -w .
        language: system
        files: \.go$