-- +goose Up
ALTER TABLE orders ADD COLUMN payment_id INTEGER DEFAULT NULL;

ALTER TABLE orders ADD CONSTRAINT FK_ORDERS_PAYMENT
    FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE SET NULL;

-- +goose Down
ALTER TABLE orders DROP CONSTRAINT FK_ORDERS_PAYMENT;
ALTER TABLE orders DROP COLUMN payment_id;