CREATE TABLE orders(
    id SERIAL PRIMARY KEY,
    user_id INTEGER DEFAULT NULL,
    total_sum DECIMAL(18, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE orders ADD CONSTRAINT FK_USER_ORDERS FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;